FROM ubuntu:20.04 AS install-dependency
RUN apt-get update && apt-get install -y \
	ca-certificates \
	git \
	wget \
	g++ \
	make \
	libssl-dev \
	git \
	&& rm -rf /var/lib/apt/lists/*
COPY .devcontainer /.devcontainer
RUN /bin/bash /.devcontainer/install_cmake.sh 3.23.2

FROM install-dependency AS build-stage
ARG OCTO_SDK_VERSION
COPY . /app
WORKDIR /app
RUN cmake -S . -B build -DCMAKE_BUILD_TYPE=release -DPLUGIN_KEY=plugin_credential.json -DOCTO_SDK_VERSION=$OCTO_SDK_VERSION
RUN cmake --build build --target package